COCO_CLASS_TRANSLATION = {
    "person": "osoba",
    "bicycle": "jízdní kolo",
    "car": "auto",
    "motorcycle": "motocykl",
    "airplane": "letadlo",
    "bus": "autobus",
    "train": "vlak",
    "truck": "nákladní auto",
    "boat": "loď",
    "traffic light": "semafor",
    "fire hydrant": "požární hydrant",
    "stop sign": "stopka",
    "parking meter": "parkovací automat",
    "bench": "lavička",
    "bird": "pták",
    "cat": "kočka",
    "dog": "pes",
    "horse": "kůň",
    "sheep": "ovce",
    "cow": "kráva",
    "elephant": "slon",
    "bear": "medvěd",
    "zebra": "zebra",
    "giraffe": "žirafa",
    "backpack": "batoh",
    "umbrella": "deštník",
    "handbag": "kabelka",
    "tie": "kravata",
    "suitcase": "kufr",
    "frisbee": "frisbee",
    "skis": "lyže",
    "snowboard": "snowboard",
    "sports ball": "míč",
    "kite": "drak",
    "baseball bat": "baseballová pálka",
    "baseball glove": "baseballová rukavice",
    "skateboard": "skateboard",
    "surfboard": "surfovací prkno",
    "tennis racket": "tenisová raketa",
    "bottle": "láhev",
    "wine glass": "sklenice na víno",
    "cup": "hrnek",
    "fork": "vidlička",
    "knife": "nůž",
    "spoon": "lžíce",
    "bowl": "miska",
    "banana": "banán",
    "apple": "jablko",
    "sandwich": "sendvič",
    "orange": "pomeranč",
    "broccoli": "brokolice",
    "carrot": "mrkev",
    "hot dog": "párek v rohlíku",
    "pizza": "pizza",
    "donut": "kobliha",
    "cake": "dort",
    "chair": "židle",
    "couch": "pohovka",
    "potted plant": "květináč",
    "bed": "postel",
    "dining table": "jídelní stůl",
    "toilet": "toaleta",
    "tv": "televizor",
    "laptop": "notebook",
    "mouse": "myš",
    "remote": "dálkový ovladač",
    "keyboard": "klávesnice",
    "cell phone": "mobilní telefon",
    "microwave": "mikrovlnná trouba",
    "oven": "trouba",
    "toaster": "toustovač",
    "sink": "dřez",
    "refrigerator": "lednice",
    "book": "kniha",
    "clock": "hodiny",
    "vase": "váza",
    "scissors": "nůžky",
    "teddy bear": "plyšový medvěd",
    "hair drier": "fén",
    "toothbrush": "zubní kartáček",
    "banner": "transparent",
    "blanket": "deka",
    "branch": "větev",
    "bridge": "most",
    "building-other": "jiná budova",
    "bush": "keř",
    "cabinet": "skříň",
    "cage": "klec",
    "card": "karta",
    "carpet": "koberec",
    "ceiling-other": "jiný strop",
    "ceiling-tile": "stropní dlaždice",
    "cloth": "látka",
    "clothes": "oblečení",
    "cloud": "mrak",
    "counter": "pult",
    "cupboard": "příborník",
    "curtain": "závěs",
    "desk-stuff": "pracovní stůl",
    "dirt": "hlína",
    "door-stuff": "dveře",
    "fence": "plot",
    "floor-marble": "mramorová podlaha",
    "floor-other": "jiná podlaha",
    "floor-stone": "kamenná podlaha",
    "floor-tile": "dlaždicová podlaha",
    "floor-wood": "dřevěná podlaha",
    "flower": "květina",
    "fog": "mlha",
    "food-other": "jiné jídlo",
    "fruit": "ovoce",
    "furniture-other": "jiný nábytek",
    "grass": "tráva",
    "gravel": "štěrk",
    "ground-other": "jiný povrch",
    "hill": "kopec",
    "house": "dům",
    "leaves": "listí",
    "light": "svítidlo",
    "mat": "rohožka",
    "mattress": "matrace",
    "mirror-stuff": "zrcadlo",
    "moss": "mech",
    "mountain": "hora",
    "mud": "bláto",
    "napkin": "ubrousek",
    "net": "síť",
    "paper": "papír",
    "pavement": "dlažba",
    "pillow": "polštář",
    "plant-other": "jiná rostlina",
    "plastic": "plast",
    "platform": "plošina",
    "building": "budova",
    "pole": "sloup",
    "road": "silnice",
    "rock": "kámen",
    "roof": "střecha",
    "roof-other": "jiná střecha",
    "rug": "koberec",
    "sand": "písek",
    "sandwich": "sendvič",
    "sea": "moře",
    "shelf": "police",
    "shelf-other": "jiná police",
    "shelf-wood": "dřevěná police",
    "metal": "kov",
    "snowman": "sněhulák",
    "mountain": "hora",
    "slope": "svah",
    "sky": "obloha",
    "tree": "strom",
    "snow": "sníh",
    "straw": "sláma",
    "table-stuff": "stůl",
    "tent": "stan",
    "tile": "dlaždice",
    "toilet-stuff": "toaleta",
    "tower": "věž",
    "tree-trunk": "kmen stromu",
    "vegetable": "zelenina",
    "wall-brick": "cihlová zeď",
    "wall-other": "jiná zeď",
    "wall-stone": "kamenná zeď",
    "wall-wood": "dřevěná zeď",
    "water-other": "jiná voda",
    "waterfall": "vodopád",
    "water-pond": "rybník",
    "water-river": "řeka",
    "water-sea": "moře",
    "water-snow": "sníh",
    "water-ice": "led",
    "water-surface": "povrch vody",
    "window-blind": "žaluzie",
    "window": "okno",
    "door": "dveře",
    "window-pane": "okno",
    "window-shutter": "okno",
    "window-wood": "dřevěné okno",
    "wood": "dřevo",
    "wood-other": "jiné dřevo",
    "wood-floor": "dřevěná podlaha",
    "wood-wall": "dřevěná zeď",
    "wood-window": "dřevěné okno",
    "ceiling": "strop",
    "wall": "zeď",
    "floor": "podlaha"
}

def preprocess_class_name(orig_label: str) -> str:
    """Zpracuje názvy tříd s příponami jako '-merged' nebo '-other-merged'"""
    base_label = orig_label.split('-')[0]
    return COCO_CLASS_TRANSLATION.get(base_label, orig_label)