import requests

def generate_text(prompt, hf_token):
    """
    Generates text based on a prompt using Hugging Face API
    
    Args:
        prompt: Text prompt for the language model
        hf_token: Hugging Face API token
        
    Returns:
        generated_text: The text generated by the model
    """
    url = "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"
    headers = {"Authorization": f"Bearer {hf_token}"}
    
    payload = {"inputs": prompt, "parameters": {"max_new_tokens": 256}}
    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Handle different response formats
    if isinstance(data, list):
        return data[0]["generated_text"]
    else:
        return data.get("generated_text", "")